
import JSZip from 'jszip';
import { ProductData } from '../types';
import { generateFileContent } from './generators';

// --- Helper Generators ---

const generateReadme = (data: ProductData): string => {
  return `# ${data.overview?.name || 'Design OS Project'}

${data.overview?.description || 'A web application generated by Design OS.'}

## Getting Started

1.  **Install dependencies:**
    \`\`\`bash
    npm install
    \`\`\`

2.  **Start the development server:**
    \`\`\`bash
    npm run dev
    \`\`\`

## Project Structure

- \`src/sections\`: Feature modules and components.
- \`src/theme\`: Design system tokens (colors, typography) and global styles.
- \`src/db\`: Prisma schema for the data layer.
- \`docs\`: Product documentation (Vision, Roadmap).

## Scripts

- \`npm run dev\`: Start Vite dev server.
- \`npm run build\`: Build for production.

Generated by Design OS.
`;
};

const generateAppTsx = (data: ProductData) => {
   const sections = data.roadmap?.sections || [];
   
   return `import React from 'react';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import './theme/global.css';

export default function App() {
  return (
    <BrowserRouter>
      <div className="min-h-screen bg-white text-zinc-900 font-sans">
        <nav className="p-4 border-b border-zinc-200 flex gap-4 overflow-x-auto">
          <Link to="/" className="font-bold shrink-0">Home</Link>
          ${sections.map(s => `<Link to="/${s.id}" className="shrink-0 hover:text-blue-600">${s.title}</Link>`).join('\n          ')}
        </nav>
        <main className="p-8 max-w-7xl mx-auto">
          <Routes>
            <Route path="/" element={
              <div className="py-12 text-center">
                <h1 className="text-4xl font-bold mb-4">Welcome to ${data.overview?.name}</h1>
                <p className="text-zinc-600">${data.overview?.description}</p>
              </div>
            } />
            {/* Section Routes */}
            ${sections.map(s => `<Route path="/${s.id}/*" element={<div className="p-4 border rounded-lg bg-zinc-50"><h2 className="text-xl font-bold mb-2">${s.title}</h2><p>Component integration needed.</p></div>} />`).join('\n            ')}
          </Routes>
        </main>
      </div>
    </BrowserRouter>
  );
}
`;
};

// --- Legacy Prompt Generators (Preserved) ---

const generateOneShotPrompt = (data: ProductData): string => {
  const vision = generateFileContent('product-vision.md', data);
  const roadmap = generateFileContent('roadmap.md', data);
  const schema = generateFileContent('schema.prisma', data);
  const types = generateFileContent('types.ts', data);
  const colors = generateFileContent('colors.ts', data);
  const typography = generateFileContent('typography.ts', data);
  
  let content = `# Project: ${data.overview?.name || 'App'} - Implementation Prompt

You are an expert Senior Full-Stack Engineer. Your task is to build the following application based on the specifications provided below.

## 1. Product Context
${vision}

## 2. Roadmap
${roadmap}

## 3. Data Model
### Schema (Prisma)
\`\`\`prisma
${schema}
\`\`\`

### Types (TypeScript)
\`\`\`typescript
${types}
\`\`\`

## 4. Design System
### Colors
\`\`\`typescript
${colors}
\`\`\`

### Typography
\`\`\`typescript
${typography}
\`\`\`
`;

  if (data.shell?.spec) {
    content += `
## 5. Application Shell
${data.shell.spec.overview}

**Navigation:**
${data.shell.spec.navigationItems.map(i => `- ${i}`).join('\n')}

**Layout Pattern:**
${data.shell.spec.layoutPattern}
`;
  }

  content += `\n## 6. Implementation Sections\n`;

  data.roadmap?.sections.forEach(section => {
    const detail = data.sections[section.id];
    if (detail?.spec) {
        content += `\n### Section: ${section.title}\n`;
        content += `${detail.spec.description}\n\n`;
        content += `**User Flows:**\n${detail.spec.userFlows.map(f => `- ${f}`).join('\n')}\n\n`;
        content += `**UI Requirements:**\n${detail.spec.uiRequirements.map(r => `- ${r}`).join('\n')}\n`;
    }
  });

  content += `\n\n## Instructions
1. Initialize the project using the tech stack implied (React, Tailwind, Prisma).
2. Implement the Design System tokens.
3. Set up the Database Schema.
4. Build the App Shell.
5. Implement each Section iteratively.
`;

  return content;
};

const generateFoundationInstructions = (data: ProductData): string => {
    return `# Milestone 0: Foundation Setup

## Goal
Initialize the project repository, install dependencies, and set up the core infrastructure (Design System & Data Layer).

## Tasks

### 1. Project Initialization
- Create a new React project (e.g., Vite + React + TypeScript).
- Install Tailwind CSS and configure \`tailwind.config.js\`.
- Install \`lucide-react\` for icons.
- Install \`clsx\` and \`tailwind-merge\` for class utilities.

### 2. Design System Setup
- Create \`src/theme/colors.ts\` and \`src/theme/typography.ts\`.
- Update \`src/index.css\` with the following CSS variables derived from the design tokens:
\`\`\`css
${generateFileContent('global.css', data)}
\`\`\`

### 3. Data Layer Setup
- Initialize Prisma: \`npx prisma init\`.
- Update \`prisma/schema.prisma\` with the following schema:
\`\`\`prisma
${generateFileContent('schema.prisma', data)}
\`\`\`
- Run \`npx prisma generate\`.
- Create \`src/types.ts\` shared types.
`;
};

const generateShellInstructions = (data: ProductData): string => {
    if (!data.shell?.spec) return '';
    return `# Milestone 1: Application Shell

## Goal
Implement the global layout, navigation, and core application wrapper.

## Specifications
${data.shell.spec.raw || data.shell.spec.overview}

## Navigation Items
${data.shell.spec.navigationItems.map(item => `- ${item}`).join('\n')}

## Tasks
1. Create \`src/components/Layout.tsx\`.
2. Implement the Sidebar/Navbar based on the navigation items.
3. Ensure responsiveness (mobile menu vs desktop sidebar).
4. Connect the layout to your router (e.g. React Router).
`;
};

const generateSectionInstructions = (sectionId: string, data: ProductData): string => {
    const section = data.roadmap?.sections.find(s => s.id === sectionId);
    const detail = data.sections[sectionId];
    if (!section || !detail?.spec) return '';

    return `# Milestone: ${section.title}

## Goal
Implement the ${section.title} feature set.

## Specification
${detail.spec.description}

### User Flows
${detail.spec.userFlows.map(f => `- [ ] ${f}`).join('\n')}

### UI Requirements
${detail.spec.uiRequirements.map(r => `- [ ] ${r}`).join('\n')}

## Implementation Steps
1. Create necessary components in \`src/sections/${sectionId}/\`.
2. Implement the screen designs.
3. Connect to the data layer (or use sample data for now).
4. Verify user flows.
`;
};

const generateSectionTests = (sectionId: string, data: ProductData): string => {
     const section = data.roadmap?.sections.find(s => s.id === sectionId);
    const detail = data.sections[sectionId];
    if (!section || !detail?.spec) return '';
    
    return `# Test Plan: ${section.title}

## User Flow Tests
${detail.spec.userFlows.map(f => `- [ ] **Test Case**: Verify ${f}`).join('\n')}

## UI/UX Checks
${detail.spec.uiRequirements.map(r => `- [ ] Verify: ${r}`).join('\n')}

## Edge Cases
- [ ] Empty state handling
- [ ] Error state handling
- [ ] Loading state handling
- [ ] Responsive layout check (Mobile/Desktop)
`;
}

// --- Main Export Function ---

export async function generateExportPackage(data: ProductData) {
  const zip = new JSZip();
  const folderName = data.overview?.name.toLowerCase().replace(/\s+/g, '-') || 'design-os-project';
  const root = zip.folder(folderName);

  if (!root) throw new Error("Failed to create zip folder");

  // 1. PROJECT BOILERPLATE (Vite + React + TS)
  root.file('README.md', generateReadme(data));
  root.file('vite.config.ts', `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()]\n});`);
  root.file('tsconfig.json', JSON.stringify({ compilerOptions: { target: "ES2020", useDefineForClassFields: true, lib: ["ES2020", "DOM", "DOM.Iterable"], module: "ESNext", skipLibCheck: true, moduleResolution: "bundler", allowImportingTsExtensions: true, resolveJsonModule: true, isolatedModules: true, noEmit: true, jsx: "react-jsx", strict: true, unusedLocals: true, noUnusedParameters: true, noFallthroughCasesInSwitch: true }, include: ["src"] }, null, 2));
  root.file('tailwind.config.js', `/** @type {import('tailwindcss').Config} */\nexport default {\n  content: [\n    "./index.html",\n    "./src/**/*.{js,ts,jsx,tsx}",\n  ],\n  theme: {\n    extend: {\n      colors: {\n        background: "var(--background)",\n        foreground: "var(--foreground)",\n        primary: "var(--primary)",\n        secondary: "var(--secondary)",\n        border: "var(--border)",\n      }\n    },\n  },\n  plugins: [],\n}`);
  root.file('postcss.config.js', `export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n}`);
  root.file('index.html', `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${data.overview?.name}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>`);
  root.file('package.json', generateFileContent('package.json', data));

  // 2. SOURCE CODE
  root.file('src/main.tsx', `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './theme/global.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n);`);
  root.file('src/App.tsx', generateAppTsx(data));

  // Data Model
  if (data.dataModel) {
    root.file('src/db/schema.prisma', generateFileContent('schema.prisma', data));
    root.file('src/types.ts', generateFileContent('types.ts', data));
  }

  // Design System
  if (data.designSystem) {
    root.file('src/theme/colors.ts', generateFileContent('colors.ts', data));
    root.file('src/theme/typography.ts', generateFileContent('typography.ts', data));
    root.file('src/theme/global.css', generateFileContent('global.css', data));
  }

  // Sections (Screens & Code)
  if (data.roadmap?.sections) {
    data.roadmap.sections.forEach(section => {
      const sectionId = section.id;
      const sectionData = data.sections[sectionId];

      if (sectionData) {
        // Sample Data
        if (sectionData.sampleData) {
           root.file(`src/sections/${sectionId}/data.json`, generateFileContent(`product/sections/${sectionId}/data.json`, data));
        }

        // Screen Designs
        if (sectionData.screens) {
            sectionData.screens.forEach(screen => {
                root.file(`src/sections/${sectionId}/${screen.componentName}.tsx`, screen.code);
            });
            
            // Index file
            root.file(`src/sections/${sectionId}/index.ts`, generateFileContent(`src/sections/${sectionId}/index.ts`, data));
        }
      }
    });
  }

  // 3. DOCUMENTATION
  root.file('docs/product-vision.md', generateFileContent('product-vision.md', data));
  if (data.roadmap) {
    root.file('docs/roadmap.md', generateFileContent('roadmap.md', data));
  }

  if (data.roadmap?.sections) {
    data.roadmap.sections.forEach(section => {
        const sectionId = section.id;
        const sectionData = data.sections[sectionId];
        if (sectionData?.spec) {
            root.file(`docs/specs/section-${sectionId}.md`, generateFileContent(`product/sections/${sectionId}/spec.md`, data));
            root.file(`docs/tests/section-${sectionId}.md`, generateSectionTests(sectionId, data));
        }
    });
  }

  // 4. CUSTOM FILES (User uploads)
  if (data.customFiles) {
    data.customFiles.forEach(file => {
        const cleanPath = file.path.startsWith('/') ? file.path.substring(1) : file.path;
        root.file(cleanPath, file.content);
    });
  }

  // 5. LEGACY/INSTRUCTION ARTIFACTS (Optional but helpful)
  root.file('prompts/one-shot-prompt.md', generateOneShotPrompt(data));
  
  const instrFolder = root.folder('instructions');
  if (instrFolder) {
      instrFolder.file('00-foundation.md', generateFoundationInstructions(data));
      if (data.shell?.spec) {
          instrFolder.file('01-shell.md', generateShellInstructions(data));
      }
      data.roadmap?.sections.forEach((section, index) => {
          const filePrefix = (index + 2).toString().padStart(2, '0');
          instrFolder.file(`${filePrefix}-section-${section.id}.md`, generateSectionInstructions(section.id, data));
      });
  }

  // Generate Blob
  const content = await zip.generateAsync({ type: 'blob' });
  return { content, filename: `${folderName}.zip` };
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
}
