
import React, { useState } from 'react';
import { DiscoveryStep, PrdContext } from '../../../types';

interface HistoryItemLockProps {
  step: DiscoveryStep;
  context: PrdContext;
  onCancel: () => void;
  onConfirm: (lockedIds: string[]) => void;
}

const HistoryItemLock: React.FC<HistoryItemLockProps> = ({ step, context, onCancel, onConfirm }) => {
  const [lockedFieldIds, setLockedFieldIds] = useState<Set<string>>(new Set());

  const toggleLock = (fieldId: string) => {
      const newSet = new Set(lockedFieldIds);
      if (newSet.has(fieldId)) newSet.delete(fieldId);
      else newSet.add(fieldId);
      setLockedFieldIds(newSet);
  };

  return (
    <div className="w-full ml-14 bg-amber-50 dark:bg-amber-900/10 p-6 rounded-2xl border-2 border-amber-400 dark:border-amber-600 shadow-xl animate-fade-in relative z-10">
        <div className="mb-4">
            <h4 className="font-bold text-amber-800 dark:text-amber-400 flex items-center gap-2">
                <i className="fa-solid fa-lock"></i> Select Fields to Keep (Lock)
            </h4>
            <p className="text-xs text-amber-700 dark:text-amber-500 mt-1">
                Unchecked fields will be regenerated by the AI based on the latest context. Locked fields will be preserved.
            </p>
        </div>
        
        <div className="space-y-3 bg-white dark:bg-slate-800 p-4 rounded-xl border border-amber-200 dark:border-amber-800/50">
            {step.fields.map(field => {
                const isLocked = lockedFieldIds.has(field.id);
                return (
                    <div 
                        key={field.id} 
                        onClick={() => toggleLock(field.id)}
                        className={`flex items-center justify-between p-3 rounded-lg border cursor-pointer transition-all
                            ${isLocked 
                                ? 'bg-amber-100 dark:bg-amber-900/30 border-amber-400 dark:border-amber-500' 
                                : 'border-slate-200 dark:border-slate-700 hover:border-amber-300 dark:hover:border-amber-700'}`}
                    >
                        <div className="flex items-center gap-3">
                            <div className={`w-5 h-5 rounded flex items-center justify-center border transition-colors
                                ${isLocked ? 'bg-amber-500 border-amber-500 text-white' : 'border-slate-300 dark:border-slate-600'}`}>
                                {isLocked && <i className="fa-solid fa-lock text-xs"></i>}
                            </div>
                            <div>
                                <span className={`text-sm font-bold block ${isLocked ? 'text-amber-900 dark:text-amber-100' : 'text-slate-700 dark:text-slate-300'}`}>{field.label}</span>
                                <span className="text-xs text-slate-500 dark:text-slate-400 truncate max-w-[200px] block">
                                    {Array.isArray(context[field.id]) ? context[field.id].join(', ') : context[field.id]}
                                </span>
                            </div>
                        </div>
                        {isLocked ? (
                            <span className="text-xs font-bold text-amber-600 dark:text-amber-400 uppercase tracking-wide">Locked</span>
                        ) : (
                            <span className="text-xs text-slate-400">Regenerate</span>
                        )}
                    </div>
                );
            })}
        </div>

        <div className="mt-6 flex justify-end gap-3">
            <button onClick={onCancel} className="px-4 py-2 text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200 text-sm font-medium">
                Cancel
            </button>
            <button onClick={() => onConfirm(Array.from(lockedFieldIds))} className="px-4 py-2 bg-amber-500 hover:bg-amber-600 text-white rounded-lg font-bold text-sm shadow transition-colors flex items-center gap-2">
                <i className="fa-solid fa-rotate-right"></i> Regenerate Step
            </button>
        </div>
    </div>
  );
};

export default HistoryItemLock;
